# -*- coding: utf-8 -*-
"""Startup Funding Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188xX4dlojpPT4T9M4o7V-N5ojQGZ4MxE

# Loading Dataset
"""

import pandas as pd
df = pd.read_csv('/content/Indian_startups_funding.csv')
df

df = df.iloc[:, 2:]
df

df.index

df.index = df.index + 1
df

"""# DATA CLEANING"""

df['startup'].values

df.info()

df['investors'].fillna('Unknown', inplace=True)

df['investors'].values

df.info()

df.dtypes

df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['year'] = df['year'].astype(int)

df.dtypes

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df['startup'] = df['startup'].str.strip().str.lower()
df['city'] = df['city'].str.strip().str.title()
df['state'] = df['state'].str.strip().str.title()

df

# top investors list (example - you can expand)
top_investors = ['Sequoia', 'Accel', 'Tiger', 'Softbank']

def investor_score(x):
    if pd.isna(x):
        return 0
    score = 0
    for inv in top_investors:
        if inv.lower() in x.lower():
            score += 1
    return score

df['investor_score'] = df['investors'].apply(investor_score)

df['startup_age_proxy'] = df['year'] - df['year'].min()

metro_cities = ['Bangalore', 'Mumbai', 'Delhi', 'Gurgaon']

df['is_metro'] = df['city'].apply(lambda x: 1 if x in metro_cities else 0)

vertical_counts = df['vertical'].value_counts()
df['vertical_freq'] = df['vertical'].map(vertical_counts)

round_map = {
    'seed': 1,
    'angel': 2,
    'series a': 3,
    'series b': 4,
    'series c': 5
}

df['round_score'] = df['round'].str.lower().map(round_map)

df['city_vertical'] = df['city'] + "_" + df['vertical']

df['investor_count'] = df['investors'].apply(lambda x: len(str(x).split(',')))

import numpy as np
y = np.log1p(df['amount'])

df.describe()

df['amount'].describe()

df['amount'].values

df = df[df['amount'] >= 0]

df['round'] = df['round'].str.lower()

df = df[df['amount'] < df['amount'].quantile(0.98)]

df['round_score'] = df['round_score'].fillna(df['round_score'].median())

"""# Feature Engineering"""

X = df.drop(columns=['amount'])   # features
import numpy as np

y = np.log1p(df['amount'])   # instead of y = df['amount']
y                  # target

X

"""one hot encoding

"""

cat_cols = X.select_dtypes(include=['object']).columns
num_cols = X.select_dtypes(exclude=['object']).columns

high_card_cols = ['startup', 'investors']
cat_cols = [col for col in cat_cols if col not in high_card_cols]

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)

from sklearn.ensemble import RandomForestRegressor

pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', RandomForestRegressor(n_estimators=200, random_state=42))
])

"""# Training the Model"""

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X.info()

pipeline.fit(X_train, y_train)

from sklearn.metrics import r2_score

y_pred = pipeline.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))

from xgboost import XGBRegressor

pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42
    ))
])
from sklearn.metrics import r2_score

# Train
pipeline.fit(X_train, y_train)

# Predict
y_pred = pipeline.predict(X_test)

# R2 Score
print("R2 Score:", r2_score(y_test, y_pred))

from sklearn.model_selection import GridSearchCV

param_grid = {
    'model__n_estimators': [200, 300, 500],
    'model__max_depth': [4, 6, 8],
    'model__learning_rate': [0.01, 0.05, 0.1],
    'model__subsample': [0.8, 1],
    'model__colsample_bytree': [0.8, 1]
}

grid = GridSearchCV(pipeline, param_grid, cv=3, scoring='r2', n_jobs=-1)

grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)

y_pred = grid.predict(X_test)
print("R2:", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipeline, X, y, cv=5, scoring='r2')

print("R2 Scores:", scores)
print("Mean R2:", scores.mean())